//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.Models.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public Tests()
        {
            this.PassedTest = new HashSet<PassedTest>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<PassedTest> PassedTest { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
