//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Service.model.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Variants = new HashSet<Variants>();
        }
    
        public int id { get; set; }
        public Nullable<int> testId { get; set; }
        public string question { get; set; }
        public string question_type { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual ICollection<Variants> Variants { get; set; }
    }
}
