//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Service.model.DatabaseEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizDBEntities : DbContext
    {
        public QuizDBEntities()
            : base("name=QuizDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answers> Answers { get; set; }
        public DbSet<PassedTest> PassedTest { get; set; }
        public DbSet<Questions> Questions { get; set; }
        public DbSet<Tests> Tests { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Variants> Variants { get; set; }
    }
}
