//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Service.model.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variants
    {
        public Variants()
        {
            this.Answers = new HashSet<Answers>();
        }
    
        public int id { get; set; }
        public string variant { get; set; }
        public Nullable<int> questionId { get; set; }
        public string imgPath { get; set; }
        public string variant_type { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
